Parameters:
  CidrBlock:
    Type: String
    Default: "10.1.0.0/16"
  PeerCidrBlock:
    Type: String
    Default: "10.0.0.0/16"

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!GetAtt VPC.CidrBlock , 1, 8]]
      Tags:
        - Key: user
          Value: karol.pucynski.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4'
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: user
          Value: karol.pucynski.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4'
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: user
          Value: karol.pucynski.labs
        - Key: stelligent-u-lesson
          Value: '4.1'
        - Key: stelligent-u-lab
          Value: '4'
  PeerRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: !Ref PeerCidrBlock
      VpcPeeringConnectionId: pcx-06efd8ebfa26d133f
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
  PeerInboundAcl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: NetworkAcl
       RuleNumber: 50
       Protocol: 6
       RuleAction: allow
       CidrBlock: !Ref PeerCidrBlock
       PortRange:
         From: 0
         To: 65535
  OutboundAcl:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: NetworkAcl
       RuleNumber: 100
       Protocol: 6
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 0
         To: 65535
  SubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref NetworkAcl
      SubnetId: !Ref Subnet

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: kpu-PeerVpcId
  SubnetId:
    Value: !Ref Subnet 
    Export:
      Name: kpu-PeerSubnetId

