Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Join
          - '-'
          - - !Ref 'AWS::AccountId'
            - !Ref BucketName
Description: 'Example s3 bucket with params'

Parameters:
  BucketName:
    Default: 'kpu-01-lab'
    Description: 'Name of the Bucket to create (globally-unique)'
    Type: String
